--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: workerhealthcheck
    group: com.bosch.cs
    team: swdc-ops
  name: workerhealthcheck
  namespace: default
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: workerhealthcheck
  template: 
    metadata: 
      annotations: 
        dapr.io/app-id: workerhealthcheck
        dapr.io/enabled: "true"
        dapr.io/log-level: debug
      labels: 
        app: workerhealthcheck
    spec:
      containers:
      - name: workerhealthcheck
        image: "sharmakartik25/msft:workerhealthcheck"
        imagePullPolicy: Always
          