apiVersion: v1
kind: Service
metadata:
  name: workerhealthcheck
  namespace: default
  labels:
    app: workerhealthcheck
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: workerhealthcheck
  type: NodePort